/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SandboxUsernameSlugRouteImport } from './routes/sandbox/$username/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxUsernameSlugRoute = SandboxUsernameSlugRouteImport.update({
  id: '/sandbox/$username/$slug',
  path: '/sandbox/$username/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sandbox/$username/$slug': typeof SandboxUsernameSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sandbox/$username/$slug': typeof SandboxUsernameSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sandbox/$username/$slug': typeof SandboxUsernameSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sandbox/$username/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sandbox/$username/$slug'
  id: '__root__' | '/' | '/sandbox/$username/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SandboxUsernameSlugRoute: typeof SandboxUsernameSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox/$username/$slug': {
      id: '/sandbox/$username/$slug'
      path: '/sandbox/$username/$slug'
      fullPath: '/sandbox/$username/$slug'
      preLoaderRoute: typeof SandboxUsernameSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SandboxUsernameSlugRoute: SandboxUsernameSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
